---
groups:
  main:
    name: Всё о самом главном
    channels:
      it52info: IT события в Нижнем Новгороде
      nnrug: lounge for developers since 2014 (тут в основном общий флудчат)

  work:
    name: Предложения и поиск работы
    channels:
      jobsit52: Вакансии в IT Нижний Новгород
      js_nn_jobs: Вакансии для фронтовиков

  languages:
    name: По языкам программирования или платформам
    channels:
      rannts: Python
      js_nn: Javascript
      golang_events_nizhny: GoLang
      nnrug: Ruby
      scala_nn: Scala
      jugnn: Java
      kotlin_nn: Kotlin
      android_nn: Android (Java, Kotlin)
      iosnndevs: iOS (Objective-C, Swift)

  interests:
    name: По интересам
    channels:
      defcon_nn_ch: новости ITSecurity
      defcon_nn: ITSecurity
      defcon_nn_offtop: ITSecurity offtop
      nnlug: NN Linux user group
      wtm_nn: Women Techmakers
      gdgnn: Google developers group
      cadr_hackerspace: Хакерспейс CADR
      qalliance: Всё о тестировании
      jenkins_nn: Чат организаторов и активистов сообщества Jenkins в Нижнем Новгороде
      jenkins_ru_events: Анонсы событий в Jenkins
      nn_cv: Машинное зрение/AR/VR
      qt_52: Чат QT сообщества
      nnov_globalcityhack: Чат участников Global City Hackathon
      gamedevnn: Разработка игр в Нижнем Новгороде
      startupnn: Cообщество для тех, у кого уже есть или кто задумывается создать свой startup
